import os
os.system("sudo apt install python3")
os.system("apt install nmap")
so.system("apt install nethogs")
so.system("apt install pyfiglet")
so.system("apt install instaloader")
so.system("apt install phonenumbers")
so.system("apt install wikipedia")
so.system("apt install psutil")
so.system("apt install GPUtil")
so.system("apt install tabulate")
so.system("apt install setuptools")
so.system("apt install playsound")
